name: "CI"
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { title: "linux"   , os: "ubuntu-latest" , cc: "clang-10", arch: "x86", build_type: "Release", defs: "SOME_PROJECT_TEST=ON" }
          - { title: "linux"   , os: "ubuntu-latest" , cc: "clang-10", arch: "x64", build_type: "Release", defs: "SOME_PROJECT_TEST=ON" }
          - { title: "windows" , os: "windows-latest", cc: "vs2019"  , arch: "x86", build_type: "Release", defs: "SOME_PROJECT_TEST=ON" }
          - { title: "windows" , os: "windows-latest", cc: "vs2019"  , arch: "x64", build_type: "Release", defs: "SOME_PROJECT_TEST=ON" }

    name: "${{matrix.title}} (${{matrix.cc}}, ${{matrix.arch}}, ${{matrix.build_type}})"
    runs-on: "${{matrix.os}}"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          path: "source"

      - name: "Checkout build-actions"
        run: git clone https://github.com/build-actions/build-actions.git build-actions --depth=1

      - name: "Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: "Prepare"
        run: python build-actions/action.py
          --step=prepare
          --compiler=${{matrix.cc}}
          --architecture=${{matrix.arch}}

      - name: "Configure"
        run: python build-actions/action.py
          --step=configure
          --config=source/.github/workflows/build-config.json
          --source-dir=source
          --compiler=${{matrix.cc}}
          --architecture=${{matrix.arch}}
          --build-type=${{matrix.build_type}}
          --build-defs=${{matrix.defs}}

      - name: "Build"
        run: python build-actions/action.py --step=build

      - name: "Test"
        run: python build-actions/action.py --step=test