name: Build and deploy C++ library

on: [push]

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        arch: [i386, x86_64, arm64, aarch64]
        include:
          - os: windows-latest
            arch: i386
            FEATURES: ["zmm", "avx512_vnni", "avx512vl", "avx_vnni", "vpclmulqdq", "avx2", "avx", "bmi2", "pclmulqdq", "sse2"]
          - os: windows-latest
            arch: x86_64
            FEATURES: ["zmm", "avx512_vnni", "avx512vl", "avx_vnni", "vpclmulqdq", "avx2", "avx", "bmi2", "pclmulqdq", "sse2"]
          - os: ubuntu-latest
            arch: arm64
            FEATURES: ["dotprod", "sha3", "prefer_pmull", "crc32", "pmull", "neon"]
          - os: ubuntu-latest
            arch: aarch64
            FEATURES: ["dotprod", "sha3", "prefer_pmull", "crc32", "pmull", "neon"]
          - os: macos-latest
            arch: arm64
            FEATURES: ["dotprod", "sha3", "prefer_pmull", "crc32", "pmull", "neon"]
          - os: macos-latest
            arch: x86_64
            FEATURES: ["zmm", "avx512_vnni", "avx512vl", "avx_vnni", "vpclmulqdq", "avx2", "avx", "bmi2", "pclmulqdq", "sse2"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake

      - name: Build library
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_SYSTEM_NAME=${matrix.os} -DCMAKE_SYSTEM_PROCESSOR=${matrix.arch} -DFEATURES=${FEATURES[*]}
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: library-${{matrix.os}}/${{matrix.arch}}
          path: build